version: "3.7"

volumes:
  db:
  
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    command: yarn run dev
    volumes: 
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
